<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Currency extends \AppBundle\Entity\Currency implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'symbol', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'exchangeRateEur', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'exchangeRateUsd', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'exchangeRateGbp', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'decimalPlaces', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'symbol', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'exchangeRateEur', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'exchangeRateUsd', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'exchangeRateGbp', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'decimalPlaces', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\Currency' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Currency $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setSymbol($symbol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSymbol', [$symbol]);

        return parent::setSymbol($symbol);
    }

    /**
     * {@inheritDoc}
     */
    public function getSymbol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSymbol', []);

        return parent::getSymbol();
    }

    /**
     * {@inheritDoc}
     */
    public function setExchangeRateEur($exchangeRateEur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExchangeRateEur', [$exchangeRateEur]);

        return parent::setExchangeRateEur($exchangeRateEur);
    }

    /**
     * {@inheritDoc}
     */
    public function getExchangeRateEur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExchangeRateEur', []);

        return parent::getExchangeRateEur();
    }

    /**
     * {@inheritDoc}
     */
    public function setExchangeRateUsd($exchangeRateUsd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExchangeRateUsd', [$exchangeRateUsd]);

        return parent::setExchangeRateUsd($exchangeRateUsd);
    }

    /**
     * {@inheritDoc}
     */
    public function getExchangeRateUsd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExchangeRateUsd', []);

        return parent::getExchangeRateUsd();
    }

    /**
     * {@inheritDoc}
     */
    public function setExchangeRateGbp($exchangeRateGbp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExchangeRateGbp', [$exchangeRateGbp]);

        return parent::setExchangeRateGbp($exchangeRateGbp);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecimalPlaces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecimalPlaces', []);

        return parent::getDecimalPlaces();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecimalPlaces($decimalPlaces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecimalPlaces', [$decimalPlaces]);

        return parent::setDecimalPlaces($decimalPlaces);
    }

    /**
     * {@inheritDoc}
     */
    public function getExchangeRateGbp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExchangeRateGbp', []);

        return parent::getExchangeRateGbp();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

}
