<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promo extends \AppBundle\Entity\Promo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'app', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'promoType', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'nUsesPerUser', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'nTotalUses', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'countNTimeUsed', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'promoCodes', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'beginAt', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'endAt', 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'app', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'promoType', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'nUsesPerUser', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'nTotalUses', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'countNTimeUsed', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'promoCodes', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'beginAt', '' . "\0" . 'AppBundle\\Entity\\Promo' . "\0" . 'endAt', 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Promo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setApp(\AppBundle\Entity\App $app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApp', [$app]);

        return parent::setApp($app);
    }

    /**
     * {@inheritDoc}
     */
    public function getApp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApp', []);

        return parent::getApp();
    }

    /**
     * {@inheritDoc}
     */
    public function addPromoCode(\AppBundle\Entity\PromoCode $promoCodes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPromoCode', [$promoCodes]);

        return parent::addPromoCode($promoCodes);
    }

    /**
     * {@inheritDoc}
     */
    public function removePromoCode(\AppBundle\Entity\PromoCode $promoCodes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePromoCode', [$promoCodes]);

        return parent::removePromoCode($promoCodes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoCodes', []);

        return parent::getPromoCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromoType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromoType', []);

        return parent::getPromoType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromoType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromoType', [$type]);

        return parent::setPromoType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function setBeginAt($beginAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeginAt', [$beginAt]);

        return parent::setBeginAt($beginAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeginAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeginAt', []);

        return parent::getBeginAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndAt($endAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndAt', [$endAt]);

        return parent::setEndAt($endAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndAt', []);

        return parent::getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getNUsesPerUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNUsesPerUser', []);

        return parent::getNUsesPerUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNUsesPerUser($nUsesPerUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNUsesPerUser', [$nUsesPerUser]);

        return parent::setNUsesPerUser($nUsesPerUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getNTotalUses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNTotalUses', []);

        return parent::getNTotalUses();
    }

    /**
     * {@inheritDoc}
     */
    public function setNTotalUses($nTotalUses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNTotalUses', [$nTotalUses]);

        return parent::setNTotalUses($nTotalUses);
    }

    /**
     * {@inheritDoc}
     */
    public function setCountNTimeUsed($countNTimeUsed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountNTimeUsed', [$countNTimeUsed]);

        return parent::setCountNTimeUsed($countNTimeUsed);
    }

    /**
     * {@inheritDoc}
     */
    public function sumCountNTimeUsed($sumCountNTimeUsed = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sumCountNTimeUsed', [$sumCountNTimeUsed]);

        return parent::sumCountNTimeUsed($sumCountNTimeUsed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountNTimeUsed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountNTimeUsed', []);

        return parent::getCountNTimeUsed();
    }

}
