<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ShopCss extends \AppBundle\Entity\ShopCss implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'cssUrl', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'productRows', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'payMethodRows', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'modular', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'hasCategories', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'public', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'active', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'apps', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'cssUrl', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'productRows', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'payMethodRows', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'modular', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'hasCategories', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'public', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'active', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'apps', '' . "\0" . 'AppBundle\\Entity\\ShopCss' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ShopCss $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCssUrl($cssUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCssUrl', [$cssUrl]);

        return parent::setCssUrl($cssUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getCssUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCssUrl', []);

        return parent::getCssUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublic($public)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublic', [$public]);

        return parent::setPublic($public);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublic', []);

        return parent::getPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function addApp(\AppBundle\Entity\App $apps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addApp', [$apps]);

        return parent::addApp($apps);
    }

    /**
     * {@inheritDoc}
     */
    public function removeApp(\AppBundle\Entity\App $apps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeApp', [$apps]);

        return parent::removeApp($apps);
    }

    /**
     * {@inheritDoc}
     */
    public function getApps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApps', []);

        return parent::getApps();
    }

    /**
     * {@inheritDoc}
     */
    public function setModular($modular)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModular', [$modular]);

        return parent::setModular($modular);
    }

    /**
     * {@inheritDoc}
     */
    public function getModular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModular', []);

        return parent::getModular();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayMethodRows($payMethodRows)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayMethodRows', [$payMethodRows]);

        return parent::setPayMethodRows($payMethodRows);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayMethodRows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayMethodRows', []);

        return parent::getPayMethodRows();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductRows($productRows)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductRows', [$productRows]);

        return parent::setProductRows($productRows);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductRows()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductRows', []);

        return parent::getProductRows();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasCategories($hasCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasCategories', [$hasCategories]);

        return parent::setHasCategories($hasCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasCategories', []);

        return parent::getHasCategories();
    }

}
