<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \AppBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'clientUsers', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'apps', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'clientApiCredential', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'affiliates', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'deposits', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'portalApp', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'ownedCurrencyLabel', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'onCreateAppActiveByDefault', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'onCreateAppCanCustomizeAppTabs', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'clientHasProviderCredentials', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'currencyEarnings', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'vatNumber', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'paysVAT', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'postalCode', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'financeEmail', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'woloPack', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'active', 'id', 'nameCompany', 'cif', 'country', 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'clientUsers', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'apps', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'clientApiCredential', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'affiliates', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'deposits', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'portalApp', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'ownedCurrencyLabel', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'onCreateAppActiveByDefault', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'onCreateAppCanCustomizeAppTabs', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'clientHasProviderCredentials', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'currencyEarnings', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'vatNumber', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'paysVAT', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'postalCode', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'address', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'financeEmail', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'logo', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'woloPack', '' . "\0" . 'AppBundle\\Entity\\Client' . "\0" . 'active', 'id', 'nameCompany', 'cif', 'country', 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(\AppBundle\Entity\Company $company)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function addClientUser(\AppBundle\Entity\ClientUser $clientUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClientUser', [$clientUsers]);

        return parent::addClientUser($clientUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClientUser(\AppBundle\Entity\ClientUser $clientUsers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClientUser', [$clientUsers]);

        return parent::removeClientUser($clientUsers);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientUsers', []);

        return parent::getClientUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortalApp($portalApp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortalApp', [$portalApp]);

        return parent::setPortalApp($portalApp);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortalApp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortalApp', []);

        return parent::getPortalApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwnedCurrencyLabel($ownedCurrencyLabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwnedCurrencyLabel', [$ownedCurrencyLabel]);

        return parent::setOwnedCurrencyLabel($ownedCurrencyLabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwnedCurrencyLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwnedCurrencyLabel', []);

        return parent::getOwnedCurrencyLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnCreateAppActiveByDefault($onCreateAppActiveByDefault)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnCreateAppActiveByDefault', [$onCreateAppActiveByDefault]);

        return parent::setOnCreateAppActiveByDefault($onCreateAppActiveByDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnCreateAppActiveByDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnCreateAppActiveByDefault', []);

        return parent::getOnCreateAppActiveByDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnCreateAppCanCustomizeAppTabs($onCreateAppCanCustomizeAppTabs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnCreateAppCanCustomizeAppTabs', [$onCreateAppCanCustomizeAppTabs]);

        return parent::setOnCreateAppCanCustomizeAppTabs($onCreateAppCanCustomizeAppTabs);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnCreateAppCanCustomizeAppTabs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnCreateAppCanCustomizeAppTabs', []);

        return parent::getOnCreateAppCanCustomizeAppTabs();
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliates', []);

        return parent::getAffiliates();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliates($affiliates)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliates', [$affiliates]);

        return parent::setAffiliates($affiliates);
    }

    /**
     * {@inheritDoc}
     */
    public function addClientHasProviderCredential(\AppBundle\Entity\ClientHasProviderCredential $clientHasProviderCredential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClientHasProviderCredential', [$clientHasProviderCredential]);

        return parent::addClientHasProviderCredential($clientHasProviderCredential);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClientHasProviderCredential(\AppBundle\Entity\ClientHasProviderCredential $clientHasProviderCredential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClientHasProviderCredential', [$clientHasProviderCredential]);

        return parent::removeClientHasProviderCredential($clientHasProviderCredential);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientHasProviderCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientHasProviderCredentials', []);

        return parent::getClientHasProviderCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getProviderClientCredentialsForApp(\AppBundle\Entity\Provider $provider, $app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProviderClientCredentialsForApp', [$provider, $app]);

        return parent::getProviderClientCredentialsForApp($provider, $app);
    }

    /**
     * {@inheritDoc}
     */
    public function addApp(\AppBundle\Entity\App $app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addApp', [$app]);

        return parent::addApp($app);
    }

    /**
     * {@inheritDoc}
     */
    public function removeApp(\AppBundle\Entity\App $app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeApp', [$app]);

        return parent::removeApp($app);
    }

    /**
     * {@inheritDoc}
     */
    public function getApps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApps', []);

        return parent::getApps();
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveApps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveApps', []);

        return parent::getActiveApps();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyEarnings($currencyEarnings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyEarnings', [$currencyEarnings]);

        return parent::setCurrencyEarnings($currencyEarnings);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyEarnings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyEarnings', []);

        return parent::getCurrencyEarnings();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function setVatNumber($vatNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVatNumber', [$vatNumber]);

        return parent::setVatNumber($vatNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getVatNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatNumber', []);

        return parent::getVatNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysVAT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysVAT', []);

        return parent::getPaysVAT();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysVAT($paysVAT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysVAT', [$paysVAT]);

        return parent::setPaysVAT($paysVAT);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode($postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', [$postalCode]);

        return parent::setPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinanceEmail($financeEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinanceEmail', [$financeEmail]);

        return parent::setFinanceEmail($financeEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinanceEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinanceEmail', []);

        return parent::getFinanceEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeposits($deposits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeposits', [$deposits]);

        return parent::setDeposits($deposits);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeposits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeposits', []);

        return parent::getDeposits();
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositCurrent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositCurrent', []);

        return parent::getDepositCurrent();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setWoloPack($woloPack)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWoloPack', [$woloPack]);

        return parent::setWoloPack($woloPack);
    }

    /**
     * {@inheritDoc}
     */
    public function getWoloPack()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWoloPack', []);

        return parent::getWoloPack();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientApiCredential(\AppBundle\Entity\ClientApiCredential $clientApiCredential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientApiCredential', [$clientApiCredential]);

        return parent::setClientApiCredential($clientApiCredential);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientApiCredential()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientApiCredential', []);

        return parent::getClientApiCredential();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameCompany($nameCompany)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameCompany', [$nameCompany]);

        return parent::setNameCompany($nameCompany);
    }

    /**
     * {@inheritDoc}
     */
    public function getNameCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameCompany', []);

        return parent::getNameCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\AppBundle\Entity\Country $country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

}
