<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AppShop extends \AppBundle\Entity\AppShop implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'appShopHasArticles', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'appShopHasAppTabs', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'active', 'app', 'levelCategory', 'valueLower', 'valueHigher', 'css', 'firstOffers', 'hasCart', 'hasCategories', 'payMethodsDefaultOrder', 'tutorialEnabled', 'tutorialPromoCode'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'appShopHasArticles', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'appShopHasAppTabs', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\AppShop' . "\0" . 'active', 'app', 'levelCategory', 'valueLower', 'valueHigher', 'css', 'firstOffers', 'hasCart', 'hasCategories', 'payMethodsDefaultOrder', 'tutorialEnabled', 'tutorialPromoCode'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AppShop $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setValueLower($valueLower)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueLower', [$valueLower]);

        return parent::setValueLower($valueLower);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueLower()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueLower', []);

        return parent::getValueLower();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function addAppShopHasArticle(\AppBundle\Entity\AppShopHasArticle $appShopHasArticles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAppShopHasArticle', [$appShopHasArticles]);

        return parent::addAppShopHasArticle($appShopHasArticles);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAppShopHasArticle(\AppBundle\Entity\AppShopHasArticle $appShopHasArticles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAppShopHasArticle', [$appShopHasArticles]);

        return parent::removeAppShopHasArticle($appShopHasArticles);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppShopHasArticles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppShopHasArticles', []);

        return parent::getAppShopHasArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function getAppShopHasArticleByArticleIdAndCountry($articleId, $countryId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppShopHasArticleByArticleIdAndCountry', [$articleId, $countryId]);

        return parent::getAppShopHasArticleByArticleIdAndCountry($articleId, $countryId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppShopHasArticleByArticleId($articleId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppShopHasArticleByArticleId', [$articleId]);

        return parent::getAppShopHasArticleByArticleId($articleId);
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppShopHasAppTabs($appShopHasAppTabs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppShopHasAppTabs', [$appShopHasAppTabs]);

        return parent::setAppShopHasAppTabs($appShopHasAppTabs);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppShopHasAppTabs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppShopHasAppTabs', []);

        return parent::getAppShopHasAppTabs();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppShopMapped(\AppBundle\Entity\AppShop $appShop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppShopMapped', [$appShop]);

        return parent::setAppShopMapped($appShop);
    }

    /**
     * {@inheritDoc}
     */
    public function setValueHigher($valueHigher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValueHigher', [$valueHigher]);

        return parent::setValueHigher($valueHigher);
    }

    /**
     * {@inheritDoc}
     */
    public function getValueHigher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValueHigher', []);

        return parent::getValueHigher();
    }

    /**
     * {@inheritDoc}
     */
    public function setApp(\AppBundle\Entity\App $app)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApp', [$app]);

        return parent::setApp($app);
    }

    /**
     * {@inheritDoc}
     */
    public function getApp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApp', []);

        return parent::getApp();
    }

    /**
     * {@inheritDoc}
     */
    public function setLevelCategory(\AppBundle\Entity\LevelCategory $levelCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLevelCategory', [$levelCategory]);

        return parent::setLevelCategory($levelCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getLevelCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevelCategory', []);

        return parent::getLevelCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstOffers($firstOffers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstOffers', [$firstOffers]);

        return parent::setFirstOffers($firstOffers);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstOffers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstOffers', []);

        return parent::getFirstOffers();
    }

    /**
     * {@inheritDoc}
     */
    public function setCss(\AppBundle\Entity\ShopCss $cssUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCss', [$cssUrl]);

        return parent::setCss($cssUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getCss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCss', []);

        return parent::getCss();
    }

    /**
     * {@inheritDoc}
     */
    public function setTutorialPromoCode(\AppBundle\Entity\PromoCode $tutorialPromo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTutorialPromoCode', [$tutorialPromo]);

        return parent::setTutorialPromoCode($tutorialPromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutorialPromoCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutorialPromoCode', []);

        return parent::getTutorialPromoCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTutorialEnabled($tutorialEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTutorialEnabled', [$tutorialEnabled]);

        return parent::setTutorialEnabled($tutorialEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getTutorialEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTutorialEnabled', []);

        return parent::getTutorialEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayMethodsDefaultOrder($payMethodsDefaultOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayMethodsDefaultOrder', [$payMethodsDefaultOrder]);

        return parent::setPayMethodsDefaultOrder($payMethodsDefaultOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayMethodsDefaultOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayMethodsDefaultOrder', []);

        return parent::getPayMethodsDefaultOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderType', []);

        return parent::getOrderType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderType($orderType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderType', [$orderType]);

        return parent::setOrderType($orderType);
    }

    /**
     * {@inheritDoc}
     */
    public function setHasCart($hasCart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasCart', [$hasCart]);

        return parent::setHasCart($hasCart);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasCart', []);

        return parent::getHasCart();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasCategories($hasCategories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasCategories', [$hasCategories]);

        return parent::setHasCategories($hasCategories);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasCategories', []);

        return parent::getHasCategories();
    }

}
