<?php

namespace AppBundle\Controller\ClientAdmin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PayMethodsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\ClientAdmin\PayMethodsController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->appShopHasArticleService = $container->get('app_shop_has_article', 1);
        return $instance;
    }
}
