<?php

namespace AppBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BillingInvoiceAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Admin\BillingInvoiceAdminController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->billingClientOwesCommand = $container->get('app.billing.client.owes_command', 1);
        return $instance;
    }
}
