<?php

namespace AppBundle\Controller\ClientAdmin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PurchasesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\ClientAdmin\PurchasesController();
        $instance->paymentProcessService = $container->get('shop.payment.payment_process', 1);
        $instance->transactionStreamHandler = $container->get('shop.logger.transaction_handler', 1);
        $instance->logger = $container->get('logger', 1);
        return $instance;
    }
}
