<?php

namespace AppBundle\Controller\AppShop;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PaymentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\AppShop\PaymentController();
        $instance->logger = $container->get('logger', 1);
        $instance->eventDispatcher = $container->get('event_dispatcher', 1);
        $instance->translator = $container->get('translator', 1);
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->router = $container->get('router', 1);
        $instance->paymentProcessService = $container->get('shop.payment.payment_process', 1);
        $instance->currencyService = $container->get('common.currency', 1);
        return $instance;
    }
}
