<?php

namespace AppBundle\Controller\AppShop;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PaymentRequirementsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\AppShop\PaymentRequirementsController();
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\PaymentRequirementsController', 'logger');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('logger', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\PaymentRequirementsController', 'validator');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('validator', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\PaymentRequirementsController', 'formHelper');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('app.form_helper', 1));
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        return $instance;
    }
}
