<?php

namespace Ibrows\SonataTranslationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TranslationCRUDController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Ibrows\SonataTranslationBundle\Controller\TranslationCRUDController();
        return $instance;
    }
}
