<?php

namespace Lexik\Bundle\TranslationBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RestController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Lexik\Bundle\TranslationBundle\Controller\RestController();
        return $instance;
    }
}
