<?php

namespace AppBundle\Entity\Enum;

class RoleEnum
{
    // Generic roles
    const SUPER_ADMIN      = 'ROLE_SUPER_ADMIN';
    const CLIENT_BASIC     = 'ROLE_CLIENT_BASIC';

    // Roles from master admin
    const SONATA_ADMIN          = 'ROLE_SONATA_ADMIN';
    const SONATA_STATS_INTERNAL = 'ROLE_SONATA_STATS_INTERNAL';
    const SONATA_FIN_MOVEMENT   = 'ROLE_SONATA_FIN_MOVEMENT';

    // Roles from transactions
    const TRANSACTION                   = 'ROLE_TRANSACTION';
    const TRANSACTION_SHOPPING          = 'ROLE_TRANSACTION_SHOPPING';
    const TRANSACTION_PAYMENT_CHECK_IN  = 'ROLE_TRANSACTION_PAYMENT_CHECK_IN';
    const TRANSACTION_PAYMENT_CHECK_OUT = 'ROLE_TRANSACTION_PAYMENT_CHECK_OUT';
    const TRANSACTION_PAYMENT_REFUND    = 'ROLE_TRANSACTION_PAYMENT_REFUND';
    const TRANSACTION_FINISHED          = 'ROLE_TRANSACTION_FINISHED';
    const TRANSACTION_PAYMENT_CANCELLED = 'ROLE_TRANSACTION_PAYMENT_CANCELLED';

    //roles from admin section
    const ADMIN_INVOICES             = 'ROLE_ADMIN_INVOICES';
    const ADMIN_CLIENT_ADMIN         = 'ROLE_ADMIN_CLIENT';
    const ADMIN_ANALITYCS            = 'ROLE_ADMIN_ANALITYCS';
    const ADMIN_TRANSACTIONS         = 'ROLE_ADMIN_TRANSACTIONS';
    const ADMIN_PURCHASES            = 'ROLE_ADMIN_PURCHASES';
    const ADMIN_PURCHASES_CANCELLATION = 'ROLE_ADMIN_PURCHASES_CANCELLATION';
    const ADMIN_NOTIFICATIONS        = 'ROLE_ADMIN_NOTIFICATIONS';
    const ADMIN_CREDENTIALS          = 'ROLE_ADMIN_CREDENTIALS';
    const ADMIN_CONFIGURE            = 'ROLE_ADMIN_CONFIGURE';
    const ADMIN_DASHBOARD            = 'ROLE_ADMIN_DASHBOARD';
    const ADMIN_SUBSCRIPTIONS        = 'ROLE_ADMIN_SUBSCRIPTIONS';
    const ADMIN_SUBSCRIPTIONS_CANCELLATION = 'ROLE_ADMIN_SUBSCRIPTIONS_CANCELLATION';
    const ADMIN_MANAGE_PROJECTS      = 'ROLE_ADMIN_MANAGE_PROJECTS';
    const ADMIN_ERRORS               = 'ROLE_ADMIN_ERRORS'; // not used
    const ADMIN_PROMO_CODES          = 'ROLE_ADMIN_PROMO_CODES';
    const ADMIN_TEST_SHOP            = 'ROLE_ADMIN_SHOP_TEST';

    // translations
    const TRANSLATOR     = 'ROLE_TRANSLATOR';

}
