<?php

namespace AppBundle\Controller\Api;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TransactionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Api\TransactionController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->paymentProcessService = $container->get('shop.payment.payment_process', 1);
        $instance->transactionCreateService = $container->get('shop.command.transaction.create', 1);
        $instance->session = $container->get('session', 1);
        $instance->paymentCompletedService = $container->get('shop.payment.completed', 1);
        $instance->container = $container;
        $instance->transactionLogger = $container->get('shop.logger.transaction_helper', 1);
        $instance->articleService = $container->get('shop_app.article', 1);
        $instance->countryService = $container->get('country', 1);
        $instance->logger = $container->get('logger', 1);
        $instance->blacklistService = $container->get('app.blacklist', 1);
        return $instance;
    }
}
