<?php

namespace AppBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TransactionAdminController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Admin\TransactionAdminController();
        return $instance;
    }
}
