<?php

namespace AppBundle\Controller\Api;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PromoCodeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Api\PromoCodeController();
        $instance->paymentProcessService = $container->get('shop.payment.payment_process', 1);
        $instance->transactionCreateService = $container->get('shop.command.transaction.create', 1);
        $instance->paymentCompletedService = $container->get('shop.payment.completed', 1);
        return $instance;
    }
}
