<?php

namespace AppBundle\Controller\Api;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PayMethodController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Api\PayMethodController();
        $instance->articleService = $container->get('shop_app.article', 1);
        $instance->articleTempPriceService = $container->get('app.article_temp_price', 1);
        $instance->payMethodService = $container->get('app.pay_method', 1);
        $instance->logger = $container->get('logger', 1);
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        return $instance;
    }
}
