<?php

namespace AppBundle\Controller\Admin;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StatsVatToPayController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Admin\StatsVatToPayController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->guzzle = $container->get('guzzle.client', 1);
        $instance->serialize = $container->get('serializer', 1);
        return $instance;
    }
}
