<?php

namespace AppBundle\Controller\AppShop;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ShopController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\AppShop\ShopController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\ShopController', 'ipInfoService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('common.ip_info', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\ShopController', 'logger');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('logger', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\ShopController', 'blacklistService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('app.blacklist', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\ShopController', 'countryService');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('country', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\ShopController', 'translator');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('translator', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\AppShop\\ShopController', 'formHelper');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('app.form_helper', 1));
        return $instance;
    }
}
