<?php

namespace AppBundle\Controller\Others;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TranslationsAngularController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Others\TranslationsAngularController();
        return $instance;
    }
}
