<?php

namespace AppBundle\Controller\Api;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CountryController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Api\CountryController();
        $instance->countryService = $container->get('country', 1);
        return $instance;
    }
}
