<?php

namespace AppBundle\Controller\AppShop;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SupportController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\AppShop\SupportController();
        return $instance;
    }
}
