<?php

namespace AppBundle\Controller\Api;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PurchaseNotificationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Api\PurchaseNotificationController();
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\Api\\PurchaseNotificationController', 'em');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('doctrine.orm.default_entity_manager', 1));
        $refProperty = new \ReflectionProperty('AppBundle\\Controller\\Api\\PurchaseNotificationController', 'notificationCommand');
        $refProperty->setAccessible(true);
        $refProperty->setValue($instance, $container->get('command.shop.app_notification.send', 1));
        return $instance;
    }
}
