<?php

namespace AppBundle\Controller\Others;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DocumentationController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Others\DocumentationController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->logger = $container->get('logger', 1);
        $instance->rootDir = $container->getParameter('kernel.root_dir');
        $instance->templating = $container->get('templating', 1);
        return $instance;
    }
}
