<?php

namespace AppBundle\Controller\Others;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class OthersController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\Others\OthersController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->guzzle = $container->get('guzzle.client', 1);
        $instance->session = $container->get('session', 1);
        $instance->currencyService = $container->get('common.currency', 1);
        return $instance;
    }
}
