<?php

namespace AppBundle\Controller\PaymentHosted;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MOLThailandController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AppBundle\Controller\PaymentHosted\MOLThailandController();
        $instance->em = $container->get('doctrine.orm.default_entity_manager', 1);
        $instance->paymentProcessService = $container->get('shop.payment.payment_process', 1);
        $instance->providerLive = $container->getParameter('payments.mol_thailand.live');
        $instance->guzzle = $container->get('guzzle.client', 1);
        $instance->router = $container->get('router', 1);
        $instance->logger = $container->get('logger', 1);
        return $instance;
    }
}
