<?php

namespace BeSimple\SoapBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SoapWebServiceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \BeSimple\SoapBundle\Controller\SoapWebServiceController();
        return $instance;
    }
}
